server:
  port: 8081



keycloak:

  auth-server-url: http://localhost:8080
  realm: Images

  resource: login-app
  public-client: true
  bearer-only: true



spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

    hikari:
      initialization-fail-timeout: 0

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update